import os

replacements = {
    'web/templates/admin.html': [
        ('Manual Emails</div>', 'رسائل يدوية</div>'),
        ('Manual Revenue</div>', 'الأرباح اليدوية</div>'),
        ('Received</div>', 'مستلم</div>'),
        ('تظهر الأكواد في الجدول أدناه — click to copy and share with users', 'تظهر الأكواد في الجدول أدناه — انقر للنسخ والمشاركة مع المستخدمين'),
        ('placeholder="Count"', 'placeholder="العدد"'),
        ('Sale (counts as revenue)', 'بيع (يُحسب كإيرادات)'),
        ('🆓 Admin Free (no revenue)', '🆓 مجاني للإدارة (بدون إيرادات)'),
        ('🆓 Admin Free Credit', '🆓 رصيد مجاني للإدارة'),
        ('Add free credits to your own wallet (not counted in revenue)', 'أضف رصيدًا مجانيًا إلى محفظتك الخاصة (لا يُحسب ضمن الإيرادات)'),
        ('🆓 Generate Admin Free Code', '🆓 إنشاء كود مجاني للإدارة'),
        ('Use at /wallet &#x2192; Redeem Code. This credit will NOT appear in profit/sales reports.', 'استخدم في /wallet &#x2192; استرداد الكود. لن يظهر هذا الرصيد في تقارير الأرباح/المبيعات.'),
        ('<h3> Give Free Campaign</h3>', '<h3> حملة مجانية</h3>'),
        ('Create a campaign for a user without charging their wallet', 'إنشاء حملة لمستخدم دون خصم من محفظته'),
        ('Give Free Campaign</button>', 'منح حملة مجانية</button>'),
        ('Send Manual Email', 'إرسال رسالة يدوية'),
        ('$0.10/email', '0.10$/رسالة'),
        ('Type any email address, subject & body — send manually via Brevo', 'اكتب أي عنوان بريد إلكتروني، موضوع، ومحتوى — للإرسال يدويًا عبر Brevo'),
        ('placeholder="Email Subject"', 'placeholder="موضوع الرسالة"'),
        ('placeholder="Email body (HTML or plain text)..."', 'placeholder="محتوى الرسالة (HTML أو نص عادي)..."'),
        ('Send Email ($0.10)', 'إرسال رسالة (0.10$)'),
        ('Flash Sale Manager', 'إدارة مبيعات الفلاش'),
        ('Create limited-time discounts to boost sales (shown as countdown timers to users)', 'إنشاء خصومات لفترة محدودة لزيادة المبيعات (تظهر كمؤقتات عد تنازلي للمستخدمين)'),
        ('placeholder="Sale title (e.g. Weekend Blast)" value="Flash Sale"', 'placeholder="عنوان التخفيض (مثل: عرض نهاية الأسبوع)" value="تخفيض فلاش"'),
        ('placeholder="Discount %"', 'placeholder="نسبة الخصم %"'),
        ('placeholder="Hours"', 'placeholder="ساعات"'),
        ('Start Flash Sale', 'بدء التخفيض'),
        ('Flash Sales (', 'مبيعات الفلاش ('),
        ('<th>ID</th><th>Title</th><th>Discount</th><th>Status</th><th>Ends</th><th>Action</th>', '<th>المعرف</th><th>العنوان</th><th>الخصم</th><th>الحالة</th><th>ينتهي</th><th>إجراء</th>'),
        ('% OFF', '% خصم'),
        ('&#x1F7E2; Active', '&#x1F7E2; نشط'),
        ('&#x1F534; Expired', '&#x1F534; منتهي'),
        ('&#x26AB; Ended', '&#x26AB; انتهى'),
        ('>End<', '>إنهاء<'),
        ('Redeem Codes (', 'أكواد الاسترداد ('),
        ('<th>Code</th><th>Value</th><th>Type</th><th>Status</th><th>Used By</th><th>Created</th>', '<th>الكود</th><th>القيمة</th><th>النوع</th><th>الحالة</th><th>استخدم بواسطة</th><th>تاريخ الإنشاء</th>'),
        ('> Copy<', '> نسخ<'),
        ('Copied!', 'تم النسخ!'),
        ('color:#fff;">🆓 Free', 'color:#fff;">🆓 مجاني'),
        ('badge-blue"> Sale', 'badge-blue"> بيع'),
        ('badge-gray">Used', 'badge-gray">مُستخدم'),
        ('badge-green">Available', 'badge-green">متاح'),
        ('No codes yet. Generate some above.', 'لا توجد أكواد بعد. قم بإنشاء البعض أعلاه.'),
        ('Users (', 'المستخدمون ('),
        ('<th>Email</th><th>Name</th><th>Type</th><th>Balance</th><th>Spent</th><th>Status</th><th>Joined</th><th>Actions</th>', '<th>البريد الإلكتروني</th><th>الاسم</th><th>النوع</th><th>الرصيد</th><th>المنفق</th><th>الحالة</th><th>انضم في</th><th>إجراءات</th>'),
        ('badge-green">Active', 'badge-green">نشط'),
        ('badge-red">Disabled', 'badge-red">معطل'),
        ('{% if u.is_active %}Disable{% else %}Enable{% endif %}', '{% if u.is_active %}تعطيل{% else %}تفعيل{% endif %}'),
        ('Recent Campaigns (', 'الحملات الأخيرة ('),
        ('<th>ID</th><th>User</th><th>Status</th><th>Companies</th><th>المرسلة</th><th>Date</th>', '<th>المعرف</th><th>المستخدم</th><th>الحالة</th><th>الشركات</th><th>المرسلة</th><th>التاريخ</th>'),
        ('No campaigns yet.', 'لا توجد حملات بعد.'),
        ('Recent Manual Emails (', 'الرسائل اليدوية الأخيرة ('),
        ('<th>To</th><th>Subject</th><th>Price</th><th>Status</th><th>Date</th>', '<th>إلى</th><th>الموضوع</th><th>السعر</th><th>الحالة</th><th>التاريخ</th>'),
        ('badge-red">Failed', 'badge-red">فشل'),
        ('Recent مدفوعات الكريبتو', 'مدفوعات الكريبتو الأخيرة'),
        ('<th>Payment ID</th><th>Order ID</th><th>Currency</th><th>Amount</th><th>TX Hash</th><th>Customer</th><th>Date</th>', '<th>معرف الدفع</th><th>معرف الطلب</th><th>العملة</th><th>المبلغ</th><th>تجزئة التحويل</th><th>العميل</th><th>التاريخ</th>'),
        ('Recent Orders (', 'الطلبات الأخيرة ('),
        ('<th>Order ID</th><th>User</th><th>Type</th><th>Amount</th><th>Status</th><th>Date</th>', '<th>معرف الطلب</th><th>المستخدم</th><th>النوع</th><th>المبلغ</th><th>الحالة</th><th>التاريخ</th>'),
        ('No orders yet.', 'لا توجد طلبات بعد.'),
        ('<h3> إضافة رصيد للمستخدم</h3>', '<h3> إضافة رصيد للمستخدم</h3>'),
        ('إضافة رصيد يدوياً لأي مستخدم', 'إضافة رصيد يدوياً لأي مستخدم')
    ],
    'web/templates/admin_analytics.html': [
        ('Admin Analytics — JobHunt Pro', 'تحليلات الإدارة — جوب هانت برو'),
        ('📊 Admin Analytics', '📊 تحليلات الإدارة'),
        ('Real-time revenue, user, and campaign metrics', 'مقاييس الأرباح، المستخدمين، والحملات في الوقت الفعلي'),
        ('Total Revenue', 'إجمالي الأرباح'),
        ('% this month', '% هذا الشهر'),
        ('Total Users', 'إجمالي المستخدمين'),
        ('new today', 'مستخدم جديد اليوم'),
        ('Campaigns Running', 'حملات قيد التشغيل'),
        ('% active rate', '% نسبة النشاط'),
        ('Emails Sent Today', 'رسائل مُرسلة اليوم'),
        ('deliverability', 'معدل التوصيل'),
        ('📈 Monthly Revenue (Last 12 Months)', '📈 الأرباح الشهرية (آخر 12 شهراً)'),
        ('💎 Revenue by Plan Tier', '💎 الأرباح حسب مستوى الخطة'),
        (' sales &middot;', ' مبيعات &middot;'),
        (' sales ·', ' مبيعات ·'),
        ('🌍 Top Markets', '🌍 أبرز الأسواق'),
        (' users &middot;', ' مستخدمين &middot;'),
        (' users ·', ' مستخدمين ·'),
        ('🧪 A/B Subject Line Testing', '🧪 اختبار أ/ب لعناوين الرسائل'),
        ('Test different email subjects to maximize open rates', 'اختبر عناوين مختلفة للرسائل لزيادة معدل الفتح'),
        ('Subject A', 'العنوان أ'),
        ('open rate &middot;', 'معدل الفتح &middot;'),
        ('open rate ·', 'معدل الفتح ·'),
        (' sent', ' مرسلة'),
        ('Subject B', 'العنوان ب')
    ],
    'web/templates/admin_user.html': [
        ('User Detail — Admin', 'تفاصيل المستخدم — الإدارة'),
        ('User: {{ user.email }}', 'مستخدم: {{ user.email }}'),
        ('Back to Admin', 'العودة للإدارة'),
        ('<h2>User Info</h2>', '<h2>معلومات المستخدم</h2>'),
        ('<label>Name</label>', '<label>الاسم</label>'),
        ('<label>Email</label>', '<label>البريد الإلكتروني</label>'),
        ('<label>Type</label>', '<label>النوع</label>'),
        ('<label>💰 Wallet</label>', '<label>💰 المحفظة</label>'),
        ('<label>Total Spent</label>', '<label>المنفق كلياً</label>'),
        ('<label>Status</label>', '<label>الحالة</label>'),
        ('badge-green">Active', 'badge-green">نشط'),
        ('badge-red">Disabled', 'badge-red">معطل'),
        ('<label>Joined</label>', '<label>انضم في</label>'),
        ('<label>API Key</label>', '<label>مفتاح API</label>'),
        ('value="Admin credit"', 'value="رصيد إدارة"'),
        ('Campaigns (', 'الحملات ('),
        ('<th>ID</th><th>Status</th><th>Companies</th><th>المرسلة</th><th>Date</th>', '<th>المعرف</th><th>الحالة</th><th>الشركات</th><th>المرسلة</th><th>التاريخ</th>'),
        ('No campaigns', 'لا توجد حملات'),
        ('Wallet Transactions (', 'معاملات المحفظة ('),
        ('<th>Type</th><th>Amount</th><th>Balance After</th><th>Description</th><th>Date</th>', '<th>النوع</th><th>المبلغ</th><th>الرصيد بعد</th><th>الوصف</th><th>التاريخ</th>'),
        ('No transactions', 'لا توجد معاملات'),
        ('Orders (', 'الطلبات ('),
        ('<th>Order ID</th><th>Type</th><th>Amount</th><th>Status</th><th>Date</th>', '<th>معرف الطلب</th><th>النوع</th><th>المبلغ</th><th>الحالة</th><th>التاريخ</th>'),
        ('No orders', 'لا توجد طلبات')
    ],
    'web/templates/antigravity.html': [
        ('INITIALIZING ANTI-GRAVITY FIELD', 'جاري تهيئة مجال انعدام الجاذبية'),
        ('AGENTS:', 'الوكلاء:'),
        ('CYCLES:', 'الدورات:'),
        ('FLOATING:', 'العناصر الطافية:'),
        ('G-FORCE:', 'قوة الجاذبية:'),
        ('CLICK TO LAUNCH // DRAG TO ROTATE // SCROLL TO ZOOM', 'انقر للإطلاق // اسحب للتدوير // مرر للتكبير'),
        ('ANTI-GRAVITY', 'انعدام الجاذبية'),
        ('GRAVITY', 'جاذبية'),
        ('BARREL ROLL', 'التفاف سريع'),
        ('SPAWN CARD', 'إضافة بطاقة'),
        ('PARTICLE BURST', 'انفجار جزيئات'),
        ('>RESET<', '>إعادة تعيين<'),
        ('>ZERO G<', '>انعدام الجاذبية<'),
        ('>GRAVITY ON<', '>الجاذبية مفعلة<'),
        ('GRAVITY ON', 'الجاذبية مفعلة'),
        ('BARREL ROLL!', 'التفاف سريع!')
    ],
    'web/templates/api_docs.html': [
        ('API Documentation — JobHunt Pro', 'وثائق واجهة برمجة التطبيقات — جوب هانت برو'),
        ('>Home<', '>الرئيسية<'),
        ('>Pricing<', '>الأسعار<'),
        ('>Blog<', '>المدونة<'),
        ('>Dashboard<', '>لوحة التحكم<'),
        ('>Get Started<', '>ابدأ الآن<'),
        ('<h1>API Documentation</h1>', '<h1>وثائق واجهة برمجة التطبيقات</h1>'),
        ('Integrate JobHunt Pro into your workflow. All API requests require authentication via your API key.', 'ادمج جوب هانت برو في سير عملك. جميع طلبات الواجهة تتطلب مصادقة باستخدام مفتاح الواجهة الخاص بك.'),
        ('<h3>Your API Key</h3>', '<h3>مفتاح واجهة برمجة التطبيقات الخاص بك</h3>'),
        ('Find your API key in the Wallet section of your dashboard. Include it in the', 'اعثر على مفتاح الواجهة الخاص بك في قسم المحفظة في لوحة التحكم. قم بتضمينه في'),
        ('header on all requests.', 'في جميع الطلبات.'),
        ('<h2>Endpoints</h2>', '<h2>النقاط الطرفية (Endpoints)</h2>'),
        ('Health Check', 'فحص الحالة'),
        ('Returns the current health status of the platform. No authentication required.', 'يُرجع حالة المنصة الحالية. لا يتطلب المصادقة.'),
        ('Get Profile', 'جلب الملف الشخصي'),
        ('Retrieve your account profile including CV data, skills, and preferences.', 'استرجع ملف حسابك بما في ذلك بيانات السيرة الذاتية، المهارات، والتفضيلات.'),
        ('<h4>Headers</h4>', '<h4>الترويسات (Headers)</h4>'),
        ('<th>Name</th><th>Type</th><th>Description</th>', '<th>الاسم</th><th>النوع</th><th>الوصف</th>'),
        ('>required<', '>مطلوب<'),
        ('Your API key', 'مفتاح الواجهة الخاص بك'),
        ('List Campaigns', 'عرض الحملات'),
        ('Retrieve all your campaigns with status and statistics.', 'استرجع جميع حملاتك مع حالتها وإحصائياتها.'),
        ('<h4>Query Parameters</h4>', '<h4>متغيرات الاستعلام (Query Parameters)</h4>'),
        ('<th>Name</th><th>Type</th><th>Default</th><th>Description</th>', '<th>الاسم</th><th>النوع</th><th>الافتراضي</th><th>الوصف</th>'),
        ('Max campaigns to return', 'الحد الأقصى للحملات المُرجعة'),
        ('Filter by status (pending, running, completed, failed)', 'تصفية حسب الحالة (قيد الانتظار، قيد التشغيل، مكتملة، فاشلة)'),
        ('Create Campaign', 'إنشاء حملة'),
        ('Create and launch a new job application campaign.', 'قم بإنشاء وإطلاق حملة تقديم للوظائف جديدة.'),
        ('<h4>Body Parameters</h4>', '<h4>متغيرات الجسم (Body Parameters)</h4>'),
        ('CV profile ID to use', 'معرف السيرة الذاتية المطلوب استخدامه'),
        ('Job search query (e.g. "network engineer")', 'استعلام البحث عن وظيفة (مثل "مهندس شبكات")'),
        ('Target location (e.g. "Dubai, UAE")', 'الموقع المستهدف (مثل "دبي، الإمارات")'),
        ('Number of companies to target', 'عدد الشركات المستهدفة'),
        ('Application Stats', 'إحصائيات التقديم'),
        ('Get aggregated statistics about your applications.', 'احصل على إحصائيات مجمعة حول تقديماتك.'),
        ('Pipeline Data', 'بيانات المسار'),
        ('Get your application pipeline with stage breakdown.', 'احصل على مسار تقديمك مع تفصيل المراحل.'),
        ('<h2>Error Codes</h2>', '<h2>رموز الأخطاء</h2>'),
        ('<th>Code</th><th>Description</th>', '<th>الرمز</th><th>الوصف</th>'),
        ('Success', 'نجاح'),
        ('Bad request &#8212; invalid parameters', 'طلب سيء &#8212; متغيرات غير صالحة'),
        ('Unauthorized &#8212; missing or invalid API key', 'غير مصرح &#8212; مفتاح واجهة مفقود أو غير صالح'),
        ('Resource not found', 'المورد غير موجود'),
        ('Rate limited &#8212; too many requests', 'تم تجاوز الحد &#8212; طلبات أكثر من اللازم'),
        ('Internal server error', 'خطأ داخلي في الخادم'),
        ('>FAQ<', '>الأسئلة الشائعة<'),
        ('>Terms<', '>الشروط<'),
        ('>Privacy<', '>الخصوصية<'),
        ('>Contact<', '>اتصل بنا<'),
        ('All rights reserved.', 'جميع الحقوق محفوظة.')
    ],
    'web/templates/ats_scorer.html': [
        ('ATS Resume Scorer', 'مقيّم السيرة الذاتية ATS'),
        ('Optimize your CV against Job Descriptions using AI-powered ATS algorithms.', 'قم بتحسين سيرتك الذاتية مقارنة بالوصف الوظيفي باستخدام خوارزميات ATS المدعومة بالذكاء الاصطناعي.'),
        ('Your Resume', 'سيرتك الذاتية'),
        ('placeholder="Paste your full resume text here...', 'placeholder="الصق النص الكامل لسيرتك الذاتية هنا...'),
        ('Paste the full text — the more detail, the better the score.', 'الصق النص الكامل — كلما زادت التفاصيل، كانت النتيجة أفضل.'),
        ('Job Description', 'الوصف الوظيفي'),
        ('placeholder="Or paste a job posting URL..."', 'placeholder="أو الصق رابط إعلان الوظيفة..."'),
        ('> Import', '> استيراد'),
        ('placeholder="Paste the job description here...', 'placeholder="الصق الوصف الوظيفي هنا...'),
        ('placeholder="Job title (optional, e.g. Senior Network Engineer)"', 'placeholder="المسمى الوظيفي (اختياري، مثلاً مهندس شبكات أول)"'),
        ('Score My Resume', 'تقييم سيرتي الذاتية'),
        ('Score Against Multiple Jobs', 'التقييم ضد وظائف متعددة'),
        ('Powered by AI Analysis', 'مدعوم بتحليل الذكاء الاصطناعي'),
        ('Bulk Scoring Results', 'نتائج التقييم المجمع'),
        ('Bulk Scoring', 'التقييم المجمع'),
        ('Add job titles to compare your resume against multiple positions at once (max 10).', 'أضف مسميات وظيفية لمقارنة سيرتك الذاتية مع مناصب متعددة في آن واحد (بحد أقصى 10).'),
        ('Run Bulk Score', 'بدء التقييم المجمع'),
        ('Add Another Job', 'إضافة وظيفة أخرى'),
        ('Analyzing Resume...', 'جاري تحليل السيرة الذاتية...'),
        ('AI is evaluating your profile against the job description.', 'الذكاء الاصطناعي يقيّم ملفك الشخصي مقارنة بالوصف الوظيفي.'),
        ('>Score<', '>النتيجة<'),
        ('Analyzing Match', 'تحليل التطابق'),
        ('Ready to process results', 'جاهز لمعالجة النتائج'),
        ('>Pending<', '>قيد الانتظار<'),
        ('Missing Keywords', 'كلمات مفتاحية مفقودة'),
        ('Strengths', 'نقاط القوة'),
        ('Suggestions', 'اقتراحات'),
        ('Excellent Match! 🌟', 'تطابق ممتاز! 🌟'),
        ('Good Match 👍', 'تطابق جيد 👍'),
        ('Average Match 🤔', 'تطابق متوسط 🤔'),
        ('Needs Work 🛠️', 'يحتاج عمل 🛠️'),
        ('Skills Match', 'تطابق المهارات'),
        ("label: 'Experience'", "label: 'الخبرة'"),
        ("label: 'Keywords'", "label: 'الكلمات المفتاحية'"),
        ("label: 'Education'", "label: 'التعليم'"),
        ("label: 'Format'", "label: 'التنسيق'"),
        ('Please paste both your resume and the job description.', 'الرجاء لصق السيرة الذاتية والوصف الوظيفي معاً.'),
        ('Both resume and job description should be at least 100 characters for a meaningful score.', 'يجب أن تحتوي السيرة الذاتية والوصف الوظيفي على 100 حرف على الأقل للحصول على تقييم ذي معنى.'),
        ('Scoring failed: ', 'فشل التقييم: '),
        ('Match for: ', 'تطابق لـ: '),
        ('ATS match analysis complete', 'اكتمل تحليل تطابق ATS'),
        ('Score: ', 'النتيجة: '),
        ('No missing keywords!', 'لا توجد كلمات مفتاحية مفقودة!'),
        ('Your resume is well-optimized!', 'سيرتك الذاتية محسنة بشكل جيد!'),
        ('Hide Bulk Mode', 'إخفاء الوضع المجمع'),
        ('placeholder="Job Title (e.g. Developer)"', 'placeholder="المسمى الوظيفي (مثل مطور)"'),
        ('placeholder="Paste JD or requirements..."', 'placeholder="الصق الوصف الوظيفي أو المتطلبات..."'),
        ('Please enter a URL to import from.', 'الرجاء إدخال رابط للاستيراد منه.'),
        ('Importing...', 'جاري الاستيراد...'),
        ("Import failed: ' + e.message + '. Try pasting the JD directly.", "فشل الاستيراد: ' + e.message + '. جرب لصق الوصف الوظيفي مباشرة."),
        ('Please paste a detailed resume first (at least 100 characters).', 'الرجاء لصق سيرة ذاتية مفصلة أولاً (على الأقل 100 حرف).'),
        ('Please add at least one job to score against.', 'الرجاء إضافة وظيفة واحدة على الأقل للتقييم ضدها.'),
        ('Bulk scoring failed: ', 'فشل التقييم المجمع: '),
        ('Best Match:', 'أفضل تطابق:'),
        ('>Job Title<', '>المسمى الوظيفي<'),
        ('>Skills<', '>المهارات<'),
        ('>Experience<', '>الخبرة<'),
        ('>Keywords<', '>الكلمات المفتاحية<')
    ],
    'web/templates/base.html': [
        ('JobHunt Pro - Enterprise AI Job Application Automator', 'جوب هانت برو - أداة أتمتة تقديم الوظائف بالذكاء الاصطناعي'),
        ('UPLINK: SECURE', 'الاتصال: آمن'),
        ('UPLINK SEVERED: RECONNECTING...', 'انقطع الاتصال: جاري إعادة الاتصال...')
    ]
}

for filepath, reps in replacements.items():
    full_path = os.path.join(r"c:\Users\samde\Desktop\📂 Folders & Projects\cv sam new ma3 kimi", filepath)
    if not os.path.exists(full_path):
        print(f"File not found: {full_path}")
        continue
    with open(full_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    for old, new in reps:
        content = content.replace(old, new)
        
    with open(full_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Processed {full_path}")
