@echo off
echo ========================================================
echo JOBHUNT PRO - MAXIMUM LEVEL EXECUTABLE (PHASE 10 ENABLED)
echo ========================================================
echo.
echo Initiating The Palantir Engine...
echo Booting Semantic Cache...
echo Engaging PostgreSQL Queue Worker...
echo Connecting to Neon.tech...
echo.
python -m uvicorn web.app_v2:app --reload --port 8000
