import re

with open(r'C:\Users\samde\Desktop\📂 Folders & Projects\cv sam new ma3 kimi\web\templates\index_v3.html', 'r', encoding='utf-8') as f:
    text = f.read()

reps = {
    'THE DIFFERENCE': 'الفرق',
    'Job Search: <span class="gradient">Before vs After</span>': 'البحث عن عمل: <span class="gradient">قبل وبعد</span>',
    'What your job hunt looks like with and without JobHunt Pro automation': 'كيف يبدو بحثك عن عمل مع وبدون أتمتة JobHunt Pro',
    'Manual Job Search': 'البحث اليدوي عن وظيفة',
    '40+ hours/week scrolling job boards': 'أكثر من 40 ساعة/أسبوع تصفح لمواقع التوظيف',
    'Copy-pasting the same cover letter': 'نسخ ولصق نفس رسالة التغطية',
    'Missing 80% of new job postings': 'تفويت 80% من الوظائف الجديدة',
    'Emails landing in spam folders': 'الإيميلات تنتهي في مجلد السبام',
    'Zero tracking on sent applications': 'انعدام التتبع للطلبات المرسلة',
    '2-3% interview rate on average': 'نسبة المقابلات 2-3% بالمتوسط',
    'Burnout within 3-4 weeks': 'إرهاق خلال 3-4 أسابيع',
    '<div class="ba-vs">VS</div>': '<div class="ba-vs">ضد</div>',
    '<div class="ba-hint">THE CHOICE IS CLEAR</div>': '<div class="ba-hint">الخيار واضح</div>',
    'JobHunt Pro Automated': 'JobHunt Pro المؤتمت',
    '0 hours/week — fully automated': '0 ساعة/أسبوع — مؤتمت بالكامل',
    'AI writes unique cover letters per company': 'الذكاء الاصطناعي يكتب رسائل تغطية فريدة لكل شركة',
    'Catches every new posting instantly': 'يلتقط كل وظيفة جديدة فوراً',
    '20+ rotating email providers = 99% inbox': '20+ مزود إيميل متناوب = 99% في صندوق الوارد',
    'Real-time dashboard tracks everything': 'لوحة تحكم حية تتبع كل شيء',
    '8-15% interview rate (4x higher)': 'نسبة المقابلات 8-15% (أعلى بـ 4 أضعاف)',
    'Sustainable — runs 24/7 while you sleep': 'مستدام — يعمل 24/7 وأنت نائم',
    
    'PLATFORM FEATURES': 'ميزات المنصة',
    'Everything You <span class="gradient">Need</span>': 'كل ما <span class="gradient">تحتاجه</span>',
    'A complete job application arsenal — every tool you need to automate your entire job search, built right in.': 'ترسانة متكاملة للتقديم على الوظائف — كل أداة تحتاجها لأتمتة بحثك بالكامل مبنية هنا.',
    'AI-Powered Personalization': 'تخصيص بالذكاء الاصطناعي',
    'Advanced AI crafts unique, personalized cover letters for every single company. Reads the job description, understands requirements, and tailors perfectly — never generic, never templated.': 'الذكاء الاصطناعي يصنع رسائل تغطية مخصصة وفريدة لكل شركة. يقرأ الوصف الوظيفي، يفهم المتطلبات، ويخصص بشكل مثالي — لا توجد قوالب عامة.',
    'Multi-Provider Email System': 'نظام إيميلات متعدد المزودين',
    'Smart rotation across 20+ email providers with intelligent warmup, spam-score checking, and automatic fallback. Your applications always land in the inbox, never in spam.': 'تناوب ذكي بين 20+ مزود إيميل مع إحماء ذكي وفحص لمستوى السبام. طلباتك تصل دائماً لصندوق الوارد، وليس السبام أبداً.',
    'Multi-Engine Job Search': 'بحث متعدد المحركات',
    'We search across all major platforms — every job board, every company career page, every listing worldwide. 50+ countries, all industries, all levels.': 'نبحث في جميع المنصات الكبرى — كل موقع توظيف، وكل صفحة وظائف شركة، وكل إعلان عالمياً. 50+ دولة، كل الصناعات، كل المستويات.',
    'Stealth Protection': 'حماية خفية',
    'Smart delays, human-like timing patterns, and sophisticated anti-detection. Email providers never flag you. Sophisticated algorithms keep you completely under the radar.': 'تأخير ذكي، توقيت يشبه البشر، وتجنب متطور للاكتشاف. خوارزمياتنا تبقيك تحت الرادار تماماً.',
    'Real-Time Analytics': 'تحليلات حية',
    'Visual pipeline tracks every application: Discovered → Applied → Followed Up → Interview → Offer. Track opens, clicks, and responses in real-time with your personal dashboard.': 'خط سير مرئي يتتبع كل طلب: اُكتشف → تم التقديم → تم المتابعة → مقابلة → عرض. تتبع الفتح، النقر، والردود بالوقت الفعلي من لوحة تحكمك الشخصية.',
    'Automatic Follow-Ups': 'متابعات تلقائية',
    'If no response, our system automatically sends polite, personalized follow-up emails. Boosts response rates by up to 40%. Never miss an opportunity because you forgot to follow up.': 'في حال عدم الرد، يقوم نظامنا بإرسال إيميلات متابعة مهذبة ومخصصة. يرفع نسبة الردود حتى 40%. لا تفوت أي فرصة فقط لأنك نسيت المتابعة.',

    'ATS RESUME CHECKER': 'فاحص السيرة الذاتية لـ ATS',
    'Is Your Resume <span class="gradient">ATS-Ready?</span>': 'هل سيرتك <span class="gradient\">جاهزة لـ ATS؟</span>',
    '99% of Fortune 500 companies use ATS. JobHunt Pro scans your resume against real job descriptions and shows exactly what to fix — <strong style="color:var(--cyan)">free</strong>.': '99% من كبرى الشركات تستخدم نظام تتبع المتقدمين (ATS). يقوم JobHunt Pro بفحص سيرتك مقابل أوصاف وظيفية حقيقية ويوضح لك بالضبط ما يجب إصلاحه — <strong style="color:var(--cyan)">مجاناً</strong>.',
    'Drag your resume here or click to upload': 'اسحب سيرتك الذاتية هنا أو انقر للرفع',
    'PDF, DOCX, or TXT (Max 5MB)': 'PDF, DOCX, أو TXT (الحد الأقصى 5 ميجابايت)',
    'Scan My Resume — Free': 'افحص سيرتي الذاتية — مجاناً',
    'Sample: Senior Network Engineer Resume': 'مثال: سيرة ذاتية لمهندس شبكات أول',
    'Keyword Match': 'تطابق الكلمات المفتاحية',
    'ATS Compatibility': 'التوافق مع ATS',
    'Format Issues': 'مشاكل التنسيق',
    'Missing Skills': 'مهارات مفقودة',
    '3 found': '3 وُجدت',

    "WHY WE'RE #1": 'لماذا نحن في الصدارة',
    'How We <span class="gradient">Compare</span>': 'كيف <span class="gradient">نقارن</span>',
    'JobHunt Pro is the only platform that automates the ENTIRE job application process': 'JobHunt Pro هي المنصة الوحيدة التي تؤتمت عملية التقديم للوظائف بأكملها',
    'Feature': 'الميزة',
    'Fully Automated Applying': 'تقديم آلي بالكامل',
    '✗ (Manual clicks)': '✗ (نقرات يدوية)',
    '✗ (Plugin only)': '✗ (إضافة متصفح فقط)',
    '✓ 100% Auto': '✓ آلي 100%',
    'Unique AI Cover Letters': 'رسائل تغطية ذكية وفريدة',
    '✗ (Generic template)': '✗ (قالب عام)',
    '✓ Every application': '✓ لكل طلب',
    'Email Inbox Delivery': 'التسليم لصندوق الوارد',
    '✗ (Often Spam)': '✗ (غالباً سبام)',
    '✓ 20+ Rotating IPs': '✓ 20+ عنوان IP متناوب',
    'Auto Follow-Ups': 'متابعات تلقائية',
    'Smart Resume Optimization': 'تحسين ذكي للسيرة',
    '✗ (Basic ATS)': '✗ (فحص أساسي)',
    '✓ Custom per job': '✓ مخصص لكل وظيفة',
    'Analytics Dashboard': 'لوحة تحكم تحليلات',
    '✓ Visual Pipeline': '✓ خط سير مرئي',
    'Multi-Engine Search': 'بحث متعدد المحركات',
    '✗ (Only LinkedIn)': '✗ (فقط LinkedIn)',
    '✗ (LinkedIn & Indeed)': '✗ (LinkedIn و Indeed)',
    '✓ 10+ Global Engines': '✓ 10+ محركات عالمية',
    'BanShield Protection': 'حماية من الحظر (BanShield)',
    '★ BanShield': '★ BanShield',
    'Crypto Payments': 'الدفع بالعملات الرقمية',
    '✓ BTC, ETH, USDT': '✓ BTC, ETH, USDT',
    'Free Tier': 'باقة مجانية',
    '★ From $2': '★ من $2',
    'Money-Back Guarantee': 'ضمان استرداد المال',
    '✓ 30-Day': '✓ 30 يوم',
    'Starting Price': 'يبدأ السعر من',
    '$99/yr': '99$/سنة',
    '$15/mo': '15$/شهر',
    'Free+': 'مجاني+',
    '$19/mo': '19$/شهر',
    '$50/mo': '50$/شهر',
    '$2 ONE-TIME': '2$ مرة واحدة',

    'LIVE PLATFORM PREVIEW': 'نظرة حية على المنصة',
    'See The <span class="gradient">Dashboard</span> In Action': 'شاهد <span class="gradient">لوحة التحكم</span> مباشرة',
    'Your personal command center for the entire job search. Real-time tracking, analytics, and insights.': 'مركز قيادتك الشخصي لكامل عملية البحث عن عمل. تتبع، تحليلات، ورؤى في الوقت الفعلي.',
    'JobHunt Pro — Live Dashboard Preview': 'JobHunt Pro — نظرة حية على لوحة التحكم',
    'Revenue Generated': 'الإيرادات المحققة',
    "Today's Activity": 'نشاط اليوم',
    'Applications Today': 'طلبات التقديم اليوم',
    'Weekly Application Performance': 'أداء التقديم الأسبوعي',
    'Open Rate': 'نسبة الفتح',
    'Response Rate': 'نسبة الرد',

    'TECH STACK & SECURITY': 'التكنولوجيا والأمان',
    'Built <span class="gradient">Professionally</span>': 'مبني <span class="gradient">باحترافية</span>',
    'Enterprise-grade infrastructure powering every application': 'بنية تحتية بمستوى المؤسسات تشغل كل طلب توظيف',
    'LPU™ Inference — fastest AI responses': 'LPU™ Inference — أسرع استجابات للذكاء الاصطناعي',
    'Enterprise email delivery & tracking': 'تسليم وتتبع الإيميلات بمستوى المؤسسات',
    'Anti-bot protection & SSL security': 'حماية من البوتات وأمان SSL',
    'BTC, ETH, USDT & 100+ crypto': 'BTC, ETH, USDT و 100+ عملة رقمية',
    'High-performance async backend': 'خلفية برمجية عالية الأداء',
    'Real-time alerts & campaign control': 'تنبيهات حية وتحكم بالحملة',

    'EARNINGS POTENTIAL': 'إمكانيات الأرباح',
    'How Much Could You <span class="gradient">Earn?</span>': 'كم يمكنك أن <span class="gradient">تربح؟</span>',
    'Set your target — we find jobs that match your salary expectations': 'حدد هدفك — نحن نجد الوظائف التي تطابق توقعات راتبك',
    '🇱🇧 Local Positions': '🇱🇧 وظائف محلية',
    '🌍 Gulf / MENA': '🌍 الخليج / الشرق الأوسط',
    '🏠 Global Remote': '🏠 عن بُعد عالمياً',
    'Estimated annual salary — Local positions': 'الراتب السنوي التقديري — وظائف محلية',
    '💡 One application costs less than 7 cents — ROI is over 100,000%': '💡 تكلفة الطلب أقل من 7 سنتات — عائد الاستثمار يتجاوز 100,000%',

    'PLATFORM POWER': 'قوة المنصة',
    'What <span class="gradient">Powers</span> Your Search': 'ما الذي <span class="gradient">يشغل</span> بحثك',
    'Enterprise-grade infrastructure working 24/7 to find your next role': 'بنية تحتية متطورة تعمل 24/7 لإيجاد وظيفتك القادمة',
    'AI Agents Working 24/7': 'وكيل ذكاء اصطناعي يعمل 24/7',
    'Countries Searched': 'دول يتم البحث فيها',
    'Email Providers Rotating': 'مزودي إيميل يتناوبون',
    'Job Search Engines': 'محركات بحث وظيفي',

    'Job Seekers Active Now': 'باحثون عن عمل نشطون الآن',
    'Applications Sent Today': 'طلبات أُرسلت اليوم',
    'Average Interview Rate': 'متوسط نسبة المقابلات',
    'Per Application Cost': 'تكلفة الطلب الواحد',

    'PRICING PLANS': 'خطط الأسعار',
    'Simple, <span class="gradient">Transparent</span> Pricing': 'أسعار بسيطة <span class="gradient">وشفافة</span>',
    'One-time payment. No subscription. No hidden fees. Pay with crypto.': 'دفع لمرة واحدة. لا اشتراكات. لا رسوم خفية. ادفع بالعملات الرقمية.',
    'Just $0.20 per company': 'فقط 0.20$ لكل شركة',
    '10 targeted applications': '10 طلبات موجهة',
    'AI-powered cover letters': 'رسائل تغطية بالذكاء الاصطناعي',
    'Basic analytics dashboard': 'لوحة تحكم تحليلات أساسية',
    'Email open tracking': 'تتبع فتح الإيميلات',
    '1 email provider': 'مزود إيميل واحد',
    '7-day support': 'دعم لمدة 7 أيام',
    'Get Started': 'ابدأ الآن',
    '🔥 MOST POPULAR': '🔥 الأكثر شعبية',
    'Just $0.05 per company': 'فقط 0.05$ لكل شركة',
    '100 targeted applications': '100 طلب موجه',
    'Advanced AI personalization': 'تخصيص متقدم بالذكاء الاصطناعي',
    'Full analytics suite': 'حزمة تحليلات كاملة',
    'Email tracking &amp; follow-ups': 'تتبع الإيميلات والمتابعة',
    '5 email providers': '5 مزودي إيميل',
    'Priority 24/7 support': 'دعم أولوية 24/7',
    'Auto follow-ups (Day 7 &amp; 14)': 'متابعات تلقائية (اليوم 7 و 14)',
    'Get Basic Now': 'احصل على الأساسية الآن',
    '⭐ BEST VALUE': '⭐ أفضل قيمة',
    'Just $0.03 per company': 'فقط 0.03$ لكل شركة',
    '💎 MOST APPLICATIONS': '💎 أكبر عدد من الطلبات',
    '500 company applications': '500 طلب للشركات',
    'Dual AI engine cover letters': 'رسائل تغطية بمحرك ذكاء اصطناعي مزدوج',
    'Real-time tracking &amp; analytics': 'تتبع وتحليلات حية',
    'Auto follow-ups (7 + 14 days)': 'متابعات تلقائية (7 + 14 يوم)',
    '200 AI agents working 24/7': '200 وكيل ذكاء اصطناعي 24/7',
    '20 email providers rotating': '20 مزود إيميل يتناوبون',
    'Company research &amp; insights': 'بحث عن الشركات ورؤى',
    'Interview preparation generator': 'مولّد التحضير للمقابلات',
    'Priority VIP support': 'دعم VIP ذو أولوية',
    '🔥 Get Pro Now': '🔥 احصل على برو الآن',
    '✨ ENTERPRISE': '✨ الشركات',
    'Just $0.025 per company': 'فقط 0.025$ لكل شركة',
    '2,000 applications': '2,000 طلب',
    'Everything in Pro +': 'كل شيء في برو +',
    'Custom AI model training': 'تدريب نموذج ذكاء اصطناعي مخصص',
    'Dedicated account manager': 'مدير حساب مخصص',
    'SLA guarantee': 'ضمان مستوى الخدمة (SLA)',
    'White-label option': 'خيار العلامة البيضاء',
    'API access': 'وصول API',
    'Multi-user dashboard': 'لوحة تحكم متعددة المستخدمين',
    'Contact Sales': 'تواصل مع المبيعات',

    'BATTLE-TESTED FEATURES': 'ميزات مُختبرة ومُثبتة',
    'What Makes <span class="gradient">JobHunt Pro</span> Different': 'ما الذي يجعل <span class="gradient">JobHunt Pro</span> مختلفاً',
    'Engineered for maximum results — every feature tested across thousands of real campaigns': 'مُصمم لأقصى النتائج — كل ميزة مُختبرة عبر آلاف الحملات الحقيقية',
    '🤖 Automated Campaign Engine': '🤖 محرك حملات آلي',
    'Our proprietary automation technology handles the heavy lifting, launching massive outreach campaigns instantly. Your profile is automatically matched and sent to thousands of employers simultaneously without any waiting queues.': 'تقنيتنا الخاصة للأتمتة تتولى العمل الشاق، وتطلق حملات تواصل ضخمة فوراً. تتم مطابقة ملفك الشخصي تلقائياً وإرساله لآلاف أصحاب العمل في نفس الوقت بدون طوابير انتظار.',
    'Lightning Fast Processing': 'معالجة بسرعة البرق',
    'Maximum Daily Applications': 'أقصى عدد طلبات يومي',
    '✉️ Enterprise Inbox Delivery': '✉️ تسليم صندوق وارد للمؤسسات',
    "We utilize advanced delivery infrastructure with intelligent routing to ensure your applications land directly in decision-makers' primary inboxes. Enjoy industry-leading deliverability while your reputation remains spotless.": 'نستخدم بنية تحتية متطورة للتسليم مع توجيه ذكي لضمان هبوط طلباتك مباشرة في صناديق الوارد الأساسية لصناع القرار. تمتع بأفضل قدرة تسليم في المجال بينما تظل سمعتك نظيفة.',
    'Premium Delivery Network': 'شبكة تسليم مميزة',
    '99.7% Inbox Delivery Rate': 'نسبة تسليم للصندوق 99.7%',
    '🧠 Advanced Personalization': '🧠 تخصيص متقدم',
    'Every application is uniquely tailored to the specific role and company. Our intelligence layer analyzes job descriptions and maps your unique skills seamlessly, ensuring you always pass automated screening tools.': 'كل طلب مصمم بشكل فريد للدور والشركة. تقوم طبقة الذكاء لدينا بتحليل أوصاف الوظائف وتعيين مهاراتك الفريدة بسلاسة، لضمان اجتيازك لأدوات الفحص الآلي دائماً.',
    'Smart Cover Letters': 'رسائل تغطية ذكية',
    'Unique formatting every time': 'تنسيق فريد في كل مرة',
    '🌍 Global Reach Network': '🌍 شبكة وصول عالمية',
    'Gain access to a massive proprietary network of job boards and private listings across 50+ countries. We pinpoint the exact roles that match your salary and location requirements without you lifting a finger.': 'احصل على وصول لشبكة خاصة ضخمة من منصات التوظيف والقوائم الخاصة في أكثر من 50 دولة. نحدد الأدوار الدقيقة التي تطابق متطلبات راتبك وموقعك دون أن ترفع إصبعاً.',
    'Worldwide Sourcing': 'بحث عالمي',
    'Exclusive Opportunities': 'فرص حصرية',
    '📊 Real-Time Insights': '📊 رؤى في الوقت الفعلي',
    'Watch your success unfold with our sleek, real-time analytics dashboard. Track when your applications are delivered, opened, and reviewed by recruiters. Stay informed with instant notifications on your mobile device.': 'شاهد نجاحك يتكشف مع لوحة تحكم التحليلات الحية الأنيقة الخاصة بنا. تتبع متى يتم تسليم طلباتك، فتحها، ومراجعتها من قبل مسؤولي التوظيف. ابقَ على اطلاع بإشعارات فورية على هاتفك المحمول.',
    'Performance Analytics': 'تحليلات الأداء',
    'Full pipeline visibility': 'رؤية كاملة لخط السير',
    '🔐 Advanced Security Protocols': '🔐 بروتوكولات أمان متقدمة',
    'Your personal data and accounts are protected by enterprise-grade security layers. We employ stealth technologies and intelligent routing to ensure your campaigns run safely, smoothly, and securely, 24/7.': 'بياناتك الشخصية وحساباتك محمية بطبقات أمان بمستوى المؤسسات. نستخدم تقنيات التخفي والتوجيه الذكي لضمان تشغيل حملاتك بأمان وسلاسة، 24/7.',
    'Enterprise Grade Security': 'أمان بمستوى المؤسسات',
    'Multi-layer protection system': 'نظام حماية متعدد الطبقات',

    'YOUR SECURITY': 'أمانك',
    'Built on <span class="gradient">Trust</span>': 'مبني على <span class="gradient">الثقة</span>',
    'Enterprise-grade security, privacy-first design, and complete data control': 'أمان بمستوى المؤسسات، تصميم يضع الخصوصية أولاً، وتحكم كامل بالبيانات',
    '256-Bit Encryption': 'تشفير 256-بت',
    'All data encrypted at rest and in transit with AES-256. Your CV and personal info are locked down tighter than Fort Knox.': 'يتم تشفير جميع البيانات أثناء النقل والحفظ باستخدام AES-256. سيرتك الذاتية ومعلوماتك الشخصية مؤمنة بقوة.',
    'GDPR Compliant': 'متوافق مع GDPR',
    'Full compliance with global privacy regulations. You control your data — download or delete it anytime, no questions asked.': 'امتثال كامل للوائح الخصوصية العالمية. أنت تتحكم في بياناتك — قم بتنزيلها أو حذفها في أي وقت.',
    'No Data Selling': 'لا لبيع البيانات',
    "We never sell, share, or monetize your personal data. Your job search is your business — we're just the engine that powers it.": 'لن نبيع أو نشارك بياناتك الشخصية أبداً. بحثك عن عمل هو شأنك الخاص — نحن فقط المحرك الذي يدعمه.',
    'Crypto-First Privacy': 'خصوصية العملات الرقمية أولاً',
    'Pay with Bitcoin, Ethereum, USDT, and more. No banks, no trace — your payment stays 100% pseudonymous. Optional email-based accounts.': 'ادفع عبر Bitcoin و Ethereum و USDT وغيرها. لا بنوك ولا تتبع — تبقى مدفوعاتك مجهولة 100%.',
    'Automated Backups': 'نسخ احتياطي تلقائي',
    'Hourly encrypted backups with 30-day retention. Your campaigns, applications, and data are always safe and recoverable.': 'نسخ احتياطي مشفر كل ساعة مع احتفاظ لمدة 30 يوماً. حملاتك وطلباتك آمنة دائماً وقابلة للاسترجاع.',
    '30-Day Money Back': 'استرداد المال خلال 30 يوم',
    'No interviews within 30 days? Get a full refund — no questions asked. We only succeed when you do. Risk-free guarantee.': 'لا مقابلات خلال 30 يوم؟ استرد كامل مبلغك — بلا أسئلة. نحن ننجح فقط عندما تنجح. ضمان خالي من المخاطر.',
    'Transparent Metrics': 'مقاييس شفافة',
    'See every application, every email open, every click. Full visibility into your campaign performance — nothing hidden.': 'شاهد كل طلب، كل فتح إيميل، كل نقرة. رؤية كاملة لأداء حملتك — لا شيء مخفي.',
    'Stealth Technology': 'تقنية التخفي',
    'Human-like timing, rotating IP patterns, and smart detection avoidance. Your applications look 100% organic. Always.': 'توقيت يحاكي البشر، وتناوب عناوين IP، وتجنب ذكي للاكتشاف. طلباتك تبدو طبيعية 100%. دائماً.',

    'GOT QUESTIONS?': 'عندك أسئلة؟',
    'Frequently <span class="gradient">Asked</span> Questions': 'الأسئلة <span class="gradient">الشائعة</span>',
    'Everything you need to know about automated job applications': 'كل ما تحتاج لمعرفته حول التقديم الآلي للوظائف',
    'How does the AI application system work?': 'كيف يعمل نظام التقديم بالذكاء الاصطناعي؟',
    'Our AI system scans thousands of job listings across multiple search engines and job boards. It analyzes each job description, then crafts personalized cover letters tailored to each specific company and role. Applications are sent through rotating email providers to ensure maximum deliverability. You simply upload your CV, set your preferences, and let the AI handle everything — 24/7, automatically.': 'يفحص نظام الذكاء الاصطناعي آلاف قوائم الوظائف. يحلل كل وصف وظيفي ثم يصنع رسائل تغطية مخصصة لكل شركة. تُرسل الطلبات عبر مزودي إيميل متناوبين لضمان أقصى قدرة تسليم. ببساطة ارفع سيرتك، حدد تفضيلاتك، ودع الذكاء الاصطناعي يتولى الباقي — 24/7، تلقائياً.',
    'Will my applications look like spam or generic templates?': 'هل ستبدو طلباتي كرسائل سبام أو قوالب عامة؟',
    'Absolutely not. Every cover letter is uniquely generated by our AI for each individual company. The AI reads the job description, extracts key requirements, and maps your skills and experience to what the employer is looking for. Each letter is different — different tone, different emphasis, different structure. Combined with our smart email rotation across 20+ providers, your applications look completely natural and never get flagged as spam.': 'إطلاقاً لا. كل رسالة تغطية تُولد بشكل فريد من قِبل الذكاء الاصطناعي لكل شركة. يقرأ الذكاء الاصطناعي الوصف الوظيفي ويربط مهاراتك بما يبحث عنه صاحب العمل. كل رسالة مختلفة تماماً. ومع التناوب الذكي للإيميلات، تبدو طلباتك طبيعية تماماً ولا تُعتبر سبام أبداً.',
    'Is there a money-back guarantee?': 'هل يوجد ضمان لاسترداد المال؟',
    "Yes! If you don't receive any interview invitations within 30 days of your campaign, we'll refund your full payment — no questions asked. We're that confident in our AI system. Over 85% of our users get at least one interview within the first 2 weeks.": 'نعم! إذا لم تتلقَ أي دعوات للمقابلات خلال 30 يوماً من حملتك، فسنقوم برد دفعتك بالكامل — بلا أسئلة. نحن واثقون بنظامنا إلى هذا الحد. أكثر من 85% من مستخدمينا يحصلون على مقابلة واحدة على الأقل خلال أول أسبوعين.',
    'What payment methods do you accept?': 'ما هي طرق الدفع المتاحة؟',
    'We accept cryptocurrency payments including Bitcoin (BTC), Ethereum (ETH), USDT (TRC-20 & ERC-20), Litecoin (LTC), Solana (SOL), and USDC. Crypto payments offer privacy, speed, and work from anywhere in the world without banking restrictions. All payments are one-time — no subscriptions, no hidden fees.': 'نقبل الدفع بالعملات الرقمية بما في ذلك Bitcoin و Ethereum و USDT و Litecoin و Solana و USDC. الدفع بالعملات الرقمية يوفر الخصوصية والسرعة ويعمل من أي مكان دون قيود مصرفية. جميع المدفوعات لمرة واحدة — لا اشتراكات، ولا رسوم خفية.',
    'Which countries and industries do you cover?': 'ما هي الدول والصناعات التي تغطيها؟',
    "We cover 50+ countries across the Middle East (Lebanon, UAE, Saudi, Qatar, Kuwait, Oman, Bahrain, Jordan, Egypt, Iraq), Europe, North America, Asia, and Australia. Our search engines scan across all major industries — technology, finance, healthcare, engineering, marketing, education, oil & gas, construction, and hundreds more. If there's a job posted online, we can find it.": 'نغطي أكثر من 50 دولة في الشرق الأوسط (لبنان، الإمارات، السعودية، قطر، الكويت، عمان، البحرين، الأردن، مصر، العراق)، أوروبا، أمريكا الشمالية، وآسيا. محركاتنا تفحص جميع الصناعات الرئيسية. إذا كان هناك وظيفة منشورة على الإنترنت، يمكننا العثور عليها.',
    'How is my data protected and my privacy maintained?': 'كيف تتم حماية بياناتي والحفاظ على خصوصيتي؟',
    "Your privacy is our top priority. Your CV data is encrypted and stored securely. We never share your information with third parties. Email providers are rotated to protect your identity. All crypto payments are pseudonymous. You maintain complete control over your data — you can delete it at any time. We don't track you, sell your data, or share anything without your explicit consent.": 'خصوصيتك هي أولويتنا القصوى. بيانات سيرتك الذاتية مشفرة. لا نشارك معلوماتك مع أطراف ثالثة أبداً. يتم تدوير مزودي الإيميل لحماية هويتك. مدفوعات العملات الرقمية مجهولة. أنت تتحكم بالكامل في بياناتك — يمكنك حذفها في أي وقت.',
    'Can I target specific companies or industries?': 'هل يمكنني استهداف شركات أو صناعات محددة؟',
    'Yes! You have full control. You can target specific job titles, industries, salary ranges, locations, company sizes, and even specific companies. Want to only apply to Fortune 500 tech companies in Dubai paying $80K+? You can do that. Want to cast a wide net across all engineering roles in the GCC? That works too. Our search filters give you complete flexibility.': 'نعم! لديك السيطرة الكاملة. يمكنك استهداف مسميات وظيفية معينة، صناعات، نطاقات رواتب، مواقع، وحتى شركات محددة. تريد التقديم فقط لشركات التقنية الكبرى في دبي براتب 80 ألف دولار+؟ يمكنك فعل ذلك.',
    'How quickly will I start seeing results?': 'متى سأبدأ في رؤية النتائج؟',
    'Applications begin within minutes of setting up your campaign. Most users see their first email opens within 24-48 hours, and interview invitations typically start arriving within 5-14 days. The speed depends on your industry, location, and target roles — but our users average an 8-15% interview rate, compared to the industry standard of 2-3%.': 'تبدأ الطلبات خلال دقائق من إعداد حملتك. يرى معظم المستخدمين أول فتح للإيميلات خلال 24-48 ساعة، وعادة ما تبدأ دعوات المقابلات بالوصول خلال 5-14 يوماً. متوسط نسبة المقابلات لدينا هو 8-15%، مقارنة بـ 2-3% للمعيار العام.',

    'VALUE ANALYSIS': 'تحليل القيمة',
    'Your <span class="gradient">ROI</span> Calculator': 'حاسبة <span class="gradient">العائد على الاستثمار</span>',
    'See how much you save by automating your job search with AI': 'شاهد كم توفر بأتمتة بحثك عن عمل عبر الذكاء الاصطناعي',
    'Your Target Annual Salary:': 'الراتب السنوي المستهدف:',
    'per month you lose by staying unemployed 1 extra month': 'شهرياً تخسرها ببقائك عاطلاً عن العمل لشهر إضافي',
    'One-Time Cost': 'تكلفة لمرة واحدة',
    'Annual Return': 'العائد السنوي',
    'ROI Multiplier': 'مضاعف العائد',
    '🚀 Invest $5 — Earn $50K+': '🚀 استثمر 5$ — اربح 50,000$+',

    'Jobs Posted Today': 'وظائف نُشرت اليوم',
    'Applications Sent in Last Hour': 'طلبات أُرسلت في آخر ساعة',
    'Limited': 'محدود',
    'Pro Plan Slots Available': 'مقاعد باقة برو المتاحة',

    '&#x1f91d; EARN WHILE YOU SHARE': '&#x1f91d; اكسب بينما تشارك',
    '<span class="gradient">Referral Program</span>': '<span class="gradient">برنامج الإحالة</span>',
    'Share JobHunt Pro with friends. They get <strong style="color:var(--cyan)">20% off</strong> their first plan, and you earn <strong style="color:var(--gold)">$5 credit</strong> for every referral that signs up. No limits.': 'شارك JobHunt Pro مع الأصدقاء. يحصلون على <strong style="color:var(--cyan)">خصم 20%</strong> على باقتهم الأولى، وتكسب أنت <strong style="color:var(--gold)">رصيد 5$</strong> لكل إحالة تسجل. بلا حدود.',
    'Share Your Link': 'شارك رابطك',
    'Copy your unique referral link from the dashboard': 'انسخ رابط الإحالة الخاص بك من لوحة التحكم',
    'They Sign Up': 'هم يسجلون',
    'Friend creates an account with any plan': 'ينشئ صديقك حساباً بأي باقة',
    'You Earn $5': 'أنت تكسب 5$',
    'Credit added instantly to your wallet': 'يُضاف الرصيد فوراً لمحفظتك',
    'Repeat': 'كرر العملية',
    'No limit — refer as many as you want': 'بلا حدود — أحِل قدر ما تشاء',
    '&#x1f517; Get Your Referral Link — Free': '&#x1f517; احصل على رابط الإحالة — مجاناً',

    'Ready to <span class="gradient">Automate</span><br>Your Job Search?': 'جاهز لـ <span class="gradient">أتمتة</span><br>بحثك عن عمل؟',
    'Stop spending hours on manual applications. Let AI do the work while you focus on what matters — preparing for interviews and landing your dream job.': 'توقف عن قضاء ساعات في التقديم اليدوي. دع الذكاء الاصطناعي يقوم بالعمل بينما تركز أنت على الأهم — التحضير للمقابلات والحصول على وظيفة أحلامك.',
    '🚀 Start Your Free Campaign Now →': '🚀 ابدأ حملتك المجانية الآن ←',
    '<strong>⚠️ Only 12 Pro Plan slots remaining this week</strong> • <strong>✓ No credit card required</strong> • Set up in 2 minutes • 30-day money-back guarantee': '<strong>⚠️ يتبقى 12 مقعداً في باقة برو هذا الأسبوع</strong> • <strong>✓ لا حاجة لبطاقة ائتمان</strong> • إعداد في دقيقتين • ضمان استرداد المال لمدة 30 يوم',

    "WAIT! Don't Leave Empty-Handed": 'انتظر! لا تغادر خالي الوفين',
    'Before you go — claim your <strong style="color:var(--cyan)">FREE ATS Resume Scan</strong> and see why your resume might be getting rejected by automated systems.': 'قبل أن تذهب — احصل على <strong style="color:var(--cyan)">فحص ATS مجاني لسيرتك الذاتية</strong> لتعرف سبب رفض الأنظمة الآلية لسيرتك.',
    '&#x2705; Instant ATS Score': '&#x2705; نتيجة ATS فورية',
    '&#x2705; Keyword Gap Analysis': '&#x2705; تحليل فجوات الكلمات المفتاحية',
    '&#x2705; 100% Free — No Card Required': '&#x2705; مجاني 100% — لا حاجة لبطاقة',
    '&#x1f50d; Scan My Resume FREE': '&#x1f50d; افحص سيرتي الذاتية مجاناً',
    'Trusted by professionals in 50+ countries': 'موثوق من المحترفين في 50+ دولة',
    '&#x1f680; Start Applying Free': '&#x1f680; ابدأ التقديم مجاناً'
}

for k, v in reps.items():
    text = text.replace(k, v)

with open(r'C:\Users\samde\Desktop\📂 Folders & Projects\cv sam new ma3 kimi\web\templates\index_v3.html', 'w', encoding='utf-8') as f:
    f.write(text)
