name = "olympus-webhook"
main = "src/index.js"
compatibility_date = "2024-06-20"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "jobhunt-pro-db"
database_id = "c477bda2-1ca3-400c-ba1a-a85716b63274"

# R2 Storage
[[r2_buckets]]
binding = "FILES"
bucket_name = "jobhunt-files"

[vars]
IPN_SECRET = "OE+zU1NbfNNlySwH3zrUthqQWZtGqrJa"
NOWPAYMENTS_API_KEY = "VA1FDVQ-JBJ41KM-QN6MVGF-TTR80X4"
PA_BASE = "https://jhfguf.pythonanywhere.com"
