"""
JobHunt Pro v13 - $0 Zero-Cost AI Video Pitch Generator
Because HeyGen costs money, this bypasses the restriction by using FFmpeg 
to generate a professional MP4 video. It combines the free Edge-TTS audio 
pitch with a static professional headshot and a dynamic audio waveform equalizer.
"""

import logging
import asyncio
import os
import time

logger = logging.getLogger(__name__)

class ZeroCostVideoPitcher:
    """
    Generates a personalized MP4 video pitch using ffmpeg.
    Requires ffmpeg installed on the system (included in Dockerfile).
    """
    def __init__(self):
        self.output_dir = "cache/video_pitches"
        self.assets_dir = "cache/assets"
        os.makedirs(self.output_dir, exist_ok=True)
        os.makedirs(self.assets_dir, exist_ok=True)
        
        # We assume a default avatar exists, if not we will generate a blank black one
        self.avatar_path = os.path.join(self.assets_dir, "professional_avatar.jpg")
        
    async def _ensure_avatar_exists(self):
        """Creates a dummy dark placeholder avatar if one isn't provided."""
        if not os.path.exists(self.avatar_path):
            try:
                # Use ffmpeg to generate a dark blue 1280x720 background
                cmd = [
                    "ffmpeg", "-y", "-f", "lavfi", "-i", "color=c=0x0D1117:s=1280x720",
                    "-vframes", "1", self.avatar_path
                ]
                process = await asyncio.create_subprocess_exec(*cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE)
                await process.communicate()
            except Exception as e:
                logger.warning(f"Failed to generate placeholder avatar: {e}")

    async def generate_video_pitch(self, audio_mp3_path: str, company: str) -> dict:
        """
        Takes an MP3 file (generated by Edge-TTS) and wraps it into a professional MP4 
        with an audio waveform visualizer.
        """
        if not os.path.exists(audio_mp3_path):
            return {"status": "error", "error": "Source audio file not found."}
            
        await self._ensure_avatar_exists()
        
        filename = f"video_pitch_{company.replace(' ', '_')}_{int(time.time())}.mp4"
        filepath = os.path.join(self.output_dir, filename)
        
        try:
            logger.info(f"Generating $0 Video Pitch for {company} using FFmpeg...")
            
            # FFmpeg complex filter:
            # 1. Take the static image as video stream
            # 2. Take the audio stream
            # 3. Generate a waveform (showwaves) from audio
            # 4. Overlay the waveform at the bottom of the image
            
            cmd = [
                "ffmpeg", "-y",
                "-loop", "1", "-i", self.avatar_path,
                "-i", audio_mp3_path,
                "-filter_complex", 
                "[1:a]showwaves=s=1280x200:mode=line:colors=cyan[wave];[0:v][wave]overlay=0:H-h[outv]",
                "-map", "[outv]", "-map", "1:a",
                "-c:v", "libx264", "-preset", "ultrafast", "-crf", "28",
                "-c:a", "aac", "-b:a", "128k",
                "-shortest", 
                filepath
            ]
            
            process = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            
            stdout, stderr = await process.communicate()
            
            if process.returncode == 0 and os.path.exists(filepath):
                logger.info(f"Video pitch successfully generated: {filepath}")
                return {"status": "success", "file_path": filepath}
            else:
                logger.error(f"FFmpeg failed: {stderr.decode()}")
                return {"status": "error", "error": "Video Generation Failed"}
                
        except Exception as e:
            logger.error(f"Exception during $0 video generation: {e}")
            return {"status": "error", "error": str(e)}

video_pitcher = ZeroCostVideoPitcher()
