import re
import os

files = [
    r'C:\Users\samde\Desktop\📂 Folders & Projects\cv sam new ma3 kimi\web\templates\services.html',
    r'C:\Users\samde\Desktop\📂 Folders & Projects\cv sam new ma3 kimi\web\templates\index_v4.html'
]

for f in files:
    with open(f, 'r', encoding='utf-8') as file:
        content = file.read()
    
    # 1. CSS Logical Properties
    content = re.sub(r'\bleft\s*:\s*0\b', 'inset-inline-start: 0', content)
    content = re.sub(r'\bright\s*:\s*0\b', 'inset-inline-end: 0', content)
    content = re.sub(r'\bmargin-left\s*:', 'margin-inline-start:', content)
    content = re.sub(r'\bpadding-left\s*:', 'padding-inline-start:', content)
    content = re.sub(r'\bborder-left\s*:', 'border-inline-start:', content)
    content = re.sub(r'\bborder-left-color\s*:', 'border-inline-start-color:', content)
    content = re.sub(r'\bright\s*:\s*-30px', 'inset-inline-end: -30px', content)
    content = re.sub(r'\bright\s*:\s*20px', 'inset-inline-end: 20px', content)
    
    # 2. Add Cairo Font
    if 'family=Cairo' not in content:
        cairo_link = '<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800&display=swap" rel="stylesheet">\n'
        content = content.replace('</head>', cairo_link + '<style>body, h1, h2, h3, h4, p, span, a, div, .btn { font-family: "Cairo", "IBM Plex Arabic", "Tajawal", sans-serif !important; }</style>\n</head>')

    # 3. Form dir auto
    content = content.replace('<input type="', '<input dir="auto" type="')
    # Cleanup if it already had dir="auto" before type
    content = content.replace('<input dir="auto" dir="auto"', '<input dir="auto"')
    
    # 4. Translations for services.html
    if 'services.html' in f:
        translations = {
            'PREMIUM <span class="cyan">SERVICES</span>': 'خدمات <span class="cyan">مميزة</span>',
            'Directly unlock high-profit expert tools using your wallet balance': 'افتح أدوات الخبراء عالية الربح مباشرة باستخدام رصيد محفظتك',
            'Wallet Balance': 'رصيد المحفظة',
            '+ Top Up': '+ تعبئة الرصيد',
            'Success!': 'نجاح!',
            'has been permanently unlocked and credited to your profile.': 'تم فتحه بشكل دائم وإضافته إلى ملفك الشخصي.',
            'Insufficient wallet balance! Please go to the': 'رصيد المحفظة غير كافٍ! يرجى الذهاب إلى',
            'page and top up to unlock this feature.': 'وتعبئة الرصيد لفتح هذه الميزة.',
            'Invalid service package selected.': 'تم تحديد باقة خدمة غير صالحة.',
            'A LA CARTE FEATURES & SERVICES': 'ميزات وخدمات حسب الطلب',
            'Unlock advanced AI optimization tools and expert features to boost your response rate. Priced between $2 and $20.': 'افتح أدوات تحسين الذكاء الاصطناعي المتقدمة وميزات الخبراء لزيادة معدل الاستجابة. بأسعار تتراوح بين 2$ و 20$.',
            'Add-on Feature': 'ميزة إضافية',
            'Price': 'السعر',
            'Unlock': 'افتح',
            'Active': 'نشط',
            'FOLLOW-UP AUTOMATION (NEW)': 'أتمتة المتابعة (جديد)',
            'AI-powered follow-up emails that automatically check in with employers who haven\'t responded. 3 tiers based on volume. Each follow-up is personalized by Groq AI.': 'رسائل بريد إلكتروني للمتابعة مدعومة بالذكاء الاصطناعي تتحقق تلقائياً مع أصحاب العمل الذين لم يردوا. 3 مستويات بناءً على الحجم. كل متابعة مخصصة بواسطة Groq AI.',
            'FOLLOW-UP TIER': 'مستوى المتابعة',
            'Per Campaign': 'لكل حملة',
            'COMBINATION BOUQUET PACKAGES': 'باقات مجمعة',
            'Combine multiple features and larger candidate reach at bulk discount pricing.': 'اجمع ميزات متعددة ووصول أكبر للمرشحين بأسعار مخفضة بالجملة.',
            'Value Bundle': 'باقة التوفير',
            'Bundle Price': 'سعر الباقة',
            'Buy Bundle': 'شراء الباقة',
            'Selected:': 'المحدد:',
            'items &nbsp;|&nbsp; Total:': 'عناصر &nbsp;|&nbsp; الإجمالي:',
            'Buy Selected': 'شراء المحدد',
            'active_upgrades_terminal.sys': 'وحدة_الترقيات_النشطة.sys',
            'SECURE CONNECTION': 'اتصال آمن',
            'SYS_UNLOCK:': 'فتح_النظام:',
            'No active system upgrades detected. Unlock features above to populate.': 'لم يتم اكتشاف ترقيات نشطة للنظام. افتح الميزات أعلاه لملئها.',
            ' Dashboard': ' لوحة التحكم',
            ' Upload CV': ' رفع السيرة الذاتية',
            ' New Campaign': ' حملة جديدة',
            ' Premium Services': ' خدمات مميزة',
            ' Wallet': ' المحفظة',
            ' Referrals': ' الإحالات',
            ' API': ' واجهة المبرمجين',
            ' Pricing Info': ' معلومات الأسعار',
            ' Logout': ' تسجيل خروج',
            ' Sent Emails': ' البريد المرسل',
            ' Stats': ' الإحصائيات',
            ' Email Test': ' اختبار البريد',
            ' Pricing': ' الأسعار',
            ' Contact': ' اتصل بنا',
            ' Export': ' تصدير',
            ' WhatsApp': ' واتساب'
        }
        for eng, ara in translations.items():
            content = content.replace(eng, ara)
            
    # 5. Translations for index_v4.html
    elif 'index_v4.html' in f:
        translations = {
            'AI SYSTEM ONLINE': 'نظام الذكاء الاصطناعي متصل',
            'Land Your Dream Job': 'احصل على وظيفة أحلامك',
            'Your personal AI job-hunting engine works <strong style="color:var(--cyan)">24/7</strong> — searching thousands of jobs,': 'محرك البحث الشخصي للوظائف بالذكاء الاصطناعي يعمل <strong style="color:var(--cyan)">24/7</strong> — يبحث في آلاف الوظائف،',
            'crafting personalized applications, and sending them through smart email rotation.': 'ينشئ طلبات تقديم مخصصة، ويرسلها عبر تناوب ذكي للبريد الإلكتروني.',
            'Start Applying Now — It\'s Free': 'ابدأ التقديم الآن — مجاناً',
            'عرض باقات الأسعار': 'عرض باقات الأسعار',
            'Featured Jobs This Week': 'وظائف مميزة هذا الأسبوع',
            'Hand-picked opportunities from our AI-powered search engine': 'فرص مختارة بعناية من محرك بحثنا المدعوم بالذكاء الاصطناعي',
            'Apply Now': 'قدم الآن',
            'Our AI is scanning': 'الذكاء الاصطناعي لدينا يمسح',
            'jobs right now': 'وظيفة الآن',
            'Unlock All Jobs': 'افتح جميع الوظائف',
            'HOW IT WORKS': 'كيف يعمل',
            'Your 24/7 AI Job-Hunting Engine': 'محرك بحث الوظائف الخاص بك 24/7 بالذكاء الاصطناعي',
            'Set up once. Our AI does the rest — applying to hundreds of jobs while you sleep.': 'قم بالإعداد مرة واحدة. الذكاء الاصطناعي يتكفل بالباقي — التقديم على مئات الوظائف أثناء نومك.',
            'AI Scans 50+ Job Boards': 'مسح أكثر من 50 موقع توظيف',
            'Our 200 AI agents search LinkedIn, Indeed, Glassdoor, Bayt, NaukriGulf, and more — finding jobs that match your profile.': 'يبحث وكلاؤنا الـ 200 المدعومون بالذكاء الاصطناعي في LinkedIn، Indeed، Glassdoor، Bayt، NaukriGulf والمزيد — لإيجاد وظائف تناسب ملفك الشخصي.',
            'Personalized Applications': 'طلبات تقديم مخصصة',
            'Each application is uniquely crafted with AI-generated cover letters, tailored resumes, and optimized answers.': 'كل طلب يُصاغ بشكل فريد مع خطابات تغطية مولدة بالذكاء الاصطناعي، سير ذاتية معدلة، وإجابات محسنة.',
            'Smart Email Rotation': 'تناوب ذكي للبريد الإلكتروني',
            '20+ email providers with intelligent rotation to maximize delivery rates and avoid spam filters.': 'أكثر من 20 مزود بريد إلكتروني مع تناوب ذكي لزيادة معدلات التسليم وتجنب فلاتر البريد المزعج.',
            'Track & Optimize': 'تتبع وتحسين',
            'Real-time dashboard shows applications sent, interview requests, and AI-powered optimization suggestions.': 'لوحة تحكم في الوقت الفعلي تظهر الطلبات المرسلة، طلبات المقابلة، واقتراحات تحسين مدعومة بالذكاء الاصطناعي.',
            'BEFORE & AFTER': 'قبل وبعد',
            'Manual vs AI-Powered Job Hunting': 'البحث اليدوي مقابل البحث بالذكاء الاصطناعي',
            'See the difference our automation makes': 'شاهد الفرق الذي يحدثه نظام الأتمتة لدينا',
            'Manual Applications': 'التقديم اليدوي',
            '3-5 applications per day': '3-5 طلبات في اليوم',
            '$0.50-$2.00 per application': '0.50$-2.00$ لكل طلب',
            'Limited to 1-2 job boards': 'محدود بـ 1-2 موقع توظيف',
            'Generic cover letters': 'خطابات تغطية عامة',
            'Manual follow-up': 'متابعة يدوية',
            '6-12 months to land a job': '6-12 شهراً للحصول على وظيفة',
            'JobHunt Pro AI': 'ذكاء اصطناعي من JobHunt Pro',
            '2,000+ applications per day': 'أكثر من 2,000 طلب يومياً',
            '<$0.07 per application': 'أقل من 0.07$ لكل طلب',
            '50+ job boards scanned': 'مسح أكثر من 50 موقع توظيف',
            'AI-personalized applications': 'طلبات مخصصة بالذكاء الاصطناعي',
            'Automated follow-up sequence': 'سلسلة متابعة آلية',
            'Get hired in 2-6 weeks': 'احصل على وظيفة خلال 2-6 أسابيع',
            'FEATURES': 'الميزات',
            'Everything You Need to Land Your Dream Job': 'كل ما تحتاجه للحصول على وظيفة أحلامك',
            '200 AI agents working around the clock to get you hired faster': '200 وكيل ذكاء اصطناعي يعملون على مدار الساعة لتوظيفك بشكل أسرع',
            '200 AI Agents': '200 وكيل ذكاء اصطناعي',
            'Distributed AI workforce that never sleeps — searching, applying, and optimizing 24/7.': 'قوة عمل موزعة من الذكاء الاصطناعي لا تنام — تبحث، تقدم، وتحسن 24/7.',
            'Multi-Engine Search': 'بحث متعدد المحركات',
            'Aggregates jobs from LinkedIn, Indeed, Glassdoor, ZipRecruiter, Bayt, NaukriGulf, Monster, and 40+ more.': 'يجمع الوظائف من LinkedIn، Indeed، Glassdoor، ZipRecruiter، Bayt، NaukriGulf، Monster، وأكثر من 40 موقعاً آخر.',
            'AI Cover Letters': 'خطابات تغطية بالذكاء الاصطناعي',
            'Each application gets a unique, context-aware cover letter tailored to the job description.': 'يحصل كل طلب على خطاب تغطية فريد ومدرك للسياق مصمم خصيصاً لوصف الوظيفة.',
            'Real-Time Dashboard': 'لوحة تحكم مباشرة',
            'Track applications, interview requests, response rates, and AI optimization suggestions.': 'تتبع الطلبات، طلبات المقابلات، معدلات الاستجابة، واقتراحات التحسين بالذكاء الاصطناعي.',
            'Privacy First': 'الخصوصية أولاً',
            'Your data is encrypted end-to-end. We never share your information with third parties.': 'بياناتك مشفرة من النهاية إلى النهاية. لا نشارك معلوماتك أبدًا مع أطراف ثالثة.',
            'ATS CHECKER': 'فاحص ATS',
            'Test Your Resume Against AI': 'اختبر سيرتك الذاتية مقابل الذكاء الاصطناعي',
            'See how your resume scores against Applicant Tracking Systems': 'شاهد كيف تسجل سيرتك الذاتية مقابل أنظمة تتبع المتقدمين',
            'Job Title': 'المسمى الوظيفي',
            'Your Skills (comma separated)': 'مهاراتك (مفصولة بفواصل)',
            'Check My Score': 'تحقق من نتيجتي',
            'Enter your details above and click "Check My Score"': 'أدخل تفاصيلك أعلاه وانقر على "تحقق من نتيجتي"',
            'COMPARISON': 'مقارنة',
            'JobHunt Pro vs The Competition': 'JobHunt Pro مقابل المنافسين',
            'See why thousands of job seekers choose us': 'اكتشف لماذا يختارنا آلاف الباحثين عن عمل',
            'Feature': 'الميزة',
            'Job Boards Scanned': 'مواقع التوظيف الممسوحة',
            'Email Rotation': 'تناوب البريد الإلكتروني',
            'Cost Per Application': 'التكلفة لكل طلب',
            'Money-Back Guarantee': 'ضمان استرداد الأموال',
            'Unique each time': 'فريد في كل مرة',
            'Template-based': 'مبني على قوالب',
            '30 Days': '30 يوماً',
            'Basic': 'أساسي',
            'LIVE DEMO': 'عرض حي',
            'See JobHunt Pro in Action': 'شاهد JobHunt Pro قيد العمل',
            'Real-time activity from our AI engine': 'نشاط في الوقت الفعلي من محرك الذكاء الاصطناعي لدينا',
            'AI Engine Dashboard — Live Feed': 'لوحة تحكم محرك الذكاء الاصطناعي — بث مباشر',
            'TECHNOLOGY': 'التكنولوجيا',
            'Powered By Cutting-Edge AI': 'مدعوم بأحدث تقنيات الذكاء الاصطناعي',
            'Built with the latest in artificial intelligence and automation technology': 'مبني بأحدث تقنيات الذكاء الاصطناعي والأتمتة',
            '50+ Job Board APIs': 'أكثر من 50 واجهة برمجة تطبيقات لمواقع التوظيف',
            '20+ SMTP Providers': 'أكثر من 20 مزود SMTP',
            'Real-Time Analytics': 'تحليلات في الوقت الفعلي',
            'AES-256 Encryption': 'تشفير AES-256',
            'Cloud Infrastructure': 'بنية تحتية سحابية',
            'Auto-Rotation System': 'نظام تناوب تلقائي',
            'Smart Matching Engine': 'محرك مطابقة ذكي',
            'ROI CALCULATOR': 'حاسبة العائد على الاستثمار',
            'Calculate Your Earnings Potential': 'احسب إمكانيات أرباحك',
            'See how much faster you can land a job with AI automation': 'اكتشف مدى سرعة حصولك على وظيفة مع أتمتة الذكاء الاصطناعي',
            'Your Target Salary ($/year)': 'الراتب المستهدف (دولار/سنة)',
            'Months Unemployed': 'أشهر البطالة',
            'Manual Applications/Day': 'الطلبات اليدوية/اليوم',
            'With JobHunt Pro': 'مع JobHunt Pro',
            'Estimated additional earnings': 'الأرباح الإضافية المقدرة',
            'Calculate My Potential': 'احسب إمكانياتي',
            'BY THE NUMBERS': 'بالأرقام',
            'JobHunt Pro in Real-Time': 'JobHunt Pro في الوقت الفعلي',
            'Live statistics from our global AI job-hunting network': 'إحصائيات حية من شبكتنا العالمية للبحث عن الوظائف بالذكاء الاصطناعي',
            'Applications Sent Today': 'الطلبات المرسلة اليوم',
            'Total Earnings (USD)': 'إجمالي الأرباح (دولار)',
            '5-Star Reviews': 'تقييمات 5 نجوم',
            'Uptime': 'وقت التشغيل',
            'applications sent today &mdash;': 'طلباً أُرسل اليوم &mdash;',
            'people got hired this week!': 'شخصاً حصلوا على وظائف هذا الأسبوع!',
            'Join Now': 'انضم الآن',
            'PRICING': 'الأسعار',
            'Invest in Your Career': 'استثمر في مسيرتك المهنية',
            'Perfect for testing the waters': 'مثالي للتجربة',
            'Best value for active job seekers': 'أفضل قيمة للباحثين النشطين عن عمل',
            'For serious job hunters': 'للباحثين الجادين عن عمل',
            'One payment. Forever access.': 'دفعة واحدة. وصول دائم.',
            '50 applications/day': '50 طلب/اليوم',
            '5 job boards': '5 مواقع توظيف',
            '3 email accounts': '3 حسابات بريد',
            'Basic dashboard': 'لوحة تحكم أساسية',
            'Priority support': 'دعم ذو أولوية',
            'Get Started': 'ابدأ الآن',
            'MOST POPULAR': 'الأكثر شعبية',
            '500 applications/day': '500 طلب/اليوم',
            '25 job boards': '25 موقع توظيف',
            '10 email accounts': '10 حسابات بريد',
            'Full dashboard + analytics': 'لوحة تحكم كاملة + تحليلات',
            'Start Now': 'ابدأ الآن',
            '2,000 applications/day': '2,000 طلب/اليوم',
            'Go Pro': 'اشترك بـ Pro',
            'Unlimited applications/day': 'طلبات غير محدودة/اليوم',
            'Priority support + API access': 'دعم أولوية + وصول API',
            'Get Lifetime': 'احصل على مدى الحياة',
            'Crypto Accepted:': 'العملات الرقمية المقبولة:',
            'RESULTS': 'النتائج',
            'Battle-Tested by Thousands': 'مُجرّب من قِبل الآلاف',
            'Real results from real job seekers who transformed their careers': 'نتائج حقيقية من باحثين حقيقيين عن عمل غيّروا مساراتهم المهنية',
            'TRUST & SECURITY': 'الثقة والأمان',
            'Your Data is Safe With Us': 'بياناتك آمنة معنا',
            'Enterprise-grade security to protect your job search': 'أمان على مستوى الشركات لحماية بحثك عن الوظائف',
            'Zero Data Sharing': 'لا مشاركة للبيانات',
            'We never sell, rent, or share your personal information with third parties.': 'نحن لا نبيع أو نؤجر أو نشارك معلوماتك الشخصية مع أطراف ثالثة أبداً.',
            'Auto-Delete Option': 'خيار الحذف التلقائي',
            'delete all your data after your job search is complete.': 'حذف كل بياناتك بعد اكتمال بحثك عن عمل.',
            'GDPR Compliant': 'متوافق مع قوانين حماية البيانات (GDPR)',
            'Fully compliant with GDPR, CCPA, and international data protection laws.': 'متوافق بالكامل مع قوانين GDPR، CCPA والقوانين الدولية لحماية البيانات.',
            '2FA Authentication': 'المصادقة الثنائية 2FA',
            'Two-factor authentication support for an extra layer of account security.': 'دعم المصادقة الثنائية لطبقة إضافية من أمان الحساب.',
            'Audit Logs': 'سجلات التدقيق',
            'Complete audit trail of all application activity for full transparency.': 'مسار تدقيق كامل لجميع أنشطة التطبيق لشفافية تامة.',
            'Enterprise-grade infrastructure with redundant systems and automatic failover.': 'بنية تحتية على مستوى الشركات مع أنظمة مكررة وتجاوز تلقائي للفشل.',
            '24/7 Support': 'دعم على مدار الساعة 24/7',
            'Our team is available around the clock to help with any issues or questions.': 'فريقنا متاح على مدار الساعة للمساعدة في أي مشكلات أو أسئلة.',
            'FAQ': 'الأسئلة الشائعة',
            'Everything you need to know about JobHunt Pro': 'كل ما تحتاج معرفته عن JobHunt Pro',
            'Ready to Land Your Dream Job?': 'هل أنت مستعد للحصول على وظيفة أحلامك؟',
            'Join thousands of successful job seekers who transformed their careers with AI-powered automation.': 'انضم إلى آلاف الباحثين عن عمل الناجحين الذين طوروا مساراتهم المهنية باستخدام أتمتة الذكاء الاصطناعي.',
            'Applications Daily': 'طلب يومياً',
            'Average Interview Rate': 'متوسط معدل المقابلات',
            'Start Your Free Trial Now': 'ابدأ تجربتك المجانية الآن',
            'No credit card required. Cancel anytime.': 'لا حاجة لبطاقة ائتمان. ألغِ في أي وقت.',
            'AI-powered automated job application engine. Apply to thousands of jobs automatically while you focus on what matters — preparing for interviews.': 'محرك بحث آلي عن الوظائف مدعوم بالذكاء الاصطناعي. قدم على آلاف الوظائف تلقائياً بينما تركز على ما يهم — التحضير للمقابلات.',
            'Product': 'المنتج',
            'Company': 'الشركة',
            'Legal': 'قانوني',
            'About Us': 'من نحن',
            'Careers': 'وظائف',
            'Press Kit': 'الملف الصحفي',
            'Partners': 'الشركاء',
            'Privacy Policy': 'سياسة الخصوصية',
            'Terms of Service': 'شروط الخدمة',
            'Cookie Policy': 'سياسة ملفات تعريف الارتباط',
            'Refund Policy': 'سياسة الاسترجاع',
            'All rights reserved.': 'جميع الحقوق محفوظة.',
            'Made with': 'صُنع بـ',
            'by AI Engineers': 'بواسطة مهندسي الذكاء الاصطناعي',
            'Wait! Don\'t Miss Out': 'انتظر! لا تفوت الفرصة',
            'Thousands of jobs are being filled right now. Start your free trial and let our AI apply for you while you\'re away.': 'آلاف الوظائف تُشغل الآن. ابدأ تجربتك المجانية ودع الذكاء الاصطناعي يقدم بالنيابة عنك أثناء غيابك.',
            'Start Free Trial': 'ابدأ التجربة المجانية',
            'No credit card required': 'لا يتطلب بطاقة ائتمان',
            'We use essential cookies to keep JobHunt Pro running. By using our site, you agree to our': 'نستخدم ملفات تعريف الارتباط الأساسية للحفاظ على عمل JobHunt Pro. باستخدامك لموقعنا، فإنك توافق على',
            'Got it': 'فهمت'
        }
        for eng, ara in translations.items():
            content = content.replace(eng, ara)

    with open(f, 'w', encoding='utf-8') as file:
        file.write(content)
