apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jobhunt-pro.fullname" . }}-frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.frontendPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
