apiVersion: v1
kind: Service
metadata:
  name: {{ include "jobhunt-pro.fullname" . }}-backend
  labels:
    app: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jobhunt-pro.fullname" . }}-frontend
  labels:
    app: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: frontend
---
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jobhunt-pro.fullname" . }}-redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: redis
{{- end }}
