#!/usr/bin/env python3
"""
JobHunt Pro — PythonAnywhere WSGI Bridge (Credential-Free Template)
====================================================================

This script renders the exact WSGI file PythonAnywhere needs to serve the
FastAPI (ASGI) app via the a2wsgi bridge. It contains NO secrets — only the
public PA username, domain, and project paths (already non-sensitive).

Usage:
    python scripts/pa_wsgi_bridge.py            # print WSGI source to stdout
    python scripts/pa_wsgi_bridge.py --write    # write to /var/www/<user>_pythonanywhere_com_wsgi.py

Override via env vars:
    PA_USER, PA_DOMAIN, PA_PROJECT_ROOT, PA_PY_VERSION
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# ── Configuration (override via env vars or edit directly) ───────────────────
PA_USER = os.getenv("PA_USER", "jhfguf")
PA_DOMAIN = os.getenv("PA_DOMAIN", f"{PA_USER}.pythonanywhere.com")
PROJECT_ROOT = os.getenv("PA_PROJECT_ROOT", f"/home/{PA_USER}/jobhunt")
PY_VERSION = os.getenv("PA_PY_VERSION", "3.12")

WSGI_PATH = f"/var/www/{PA_USER}_pythonanywhere_com_wsgi.py"


def build_wsgi_source() -> str:
    """Return the full WSGI file source as a string."""
    return f'''# /var/www/{PA_USER}_pythonanywhere_com_wsgi.py
# Auto-generated by scripts/pa_wsgi_bridge.py — JobHunt Pro
import sys
from pathlib import Path

# Make the project root importable so `import web.app_v2` resolves.
PROJECT_ROOT = Path(r"{PROJECT_ROOT}")
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Virtualenv site-packages (uncomment if using a venv)
# sys.path.insert(0, "{PROJECT_ROOT}/venv/lib/python{PY_VERSION}/site-packages")

# a2wsgi bridges the FastAPI (ASGI) app to WSGI for PythonAnywhere.
from a2wsgi import ASGIMiddleware
from web.app_v2 import app

# WSGI entrypoint consumed by PythonAnywhere's Apache/uwsgi.
try:
    wsgi_app = ASGIMiddleware(app, send_queue_size=20)
except TypeError:
    wsgi_app = ASGIMiddleware(app)
'''


def render_wsgi_file(write: bool = False) -> str:
    """Render (and optionally write) the WSGI file."""
    source = build_wsgi_source()
    if write:
        Path(WSGI_PATH).write_text(source, encoding="utf-8")
        print(f"[WSGI] Written to {WSGI_PATH}")
    else:
        print(source)
    return source


if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Render JobHunt Pro PA WSGI file")
    p.add_argument("--write", action="store_true",
                   help="Write to WSGI_PATH instead of printing to stdout")
    args = p.parse_args()
    render_wsgi_file(write=args.write)
