name = "jobhunt-pro-keepalive"
main = "src/index.js"
compatibility_date = "2026-01-01"

[vars]
PRIMARY_URL = "https://jobhunt-pro.onrender.com/ping"
BACKEND_URL = "https://jhfguf.pythonanywhere.com/ping"
KOYEB_URL = "https://jobhunt-pro-koyeb.koyeb.app/ping"
APP_URL = "https://jobhunt-pro.onrender.com/ping"
ENGINE_URL = "https://jobhunt-pro-engine.onrender.com/ping"

[triggers]
crons = ["*/4 * * * *"]
