name: PythonAnywhere Auto Renew

on:
  schedule:
    - cron: "0 0 1,15 * *" # Runs at midnight on the 1st and 15th of every month
  workflow_dispatch: # Allows manual trigger

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests pyotp beautifulsoup4

      - name: Run Auto-Renew Script
        run: python scripts/pythonanywhere_auto_extend.py

